id: IE92270F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:15:46+00:00'
last_modified: '2022-06-09T04:43:34.650320+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5651
  title: འབྲོང་སྟག་ཐང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    05DF:
      image_group_id: I3CN5653
      title: Volume 1 of 'brong stag thang /
      total_pages: 416
      order: 1
      base_file: 05DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
