id: P008132
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5651
  title: འབྲོང་སྟག་ཐང་།
  author: ''
  volumes:
    80d7f378a8214fbfb6f8620d28d5414e:
      image_group_id: I3CN5653
      title: ''
      volume_number: 1
      total_pages: 416
ebook_metadata:
  title: འབྲོང་སྟག་ཐང་།
  author: ''
  sku: P008132
  cover: cover.jpg
  layers:
  - pagination
